[project]
authors = ["neverorfrog <97flavio.maiorana@gmail.com>"]
channels = ["robostack-humble", "conda-forge"]
description = "Add a short description here"
name = "ismpc-ros2"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
build = {cmd = "colcon build", inputs = ["src"]}
clean = "rm -rf install log build"
ismpc = "ros2 launch ismpc_ros_client ismpc.launch.py"
# build-run-ismpc = "colcon build && ros2 launch ismpc_client ismpc.launch.py"

[activation]
scripts = ["install/setup.sh"]

[dependencies]
python = "3.11.*"
ros-humble-desktop = ">=0.10.0,<0.11"
ros-humble-ament-cmake-auto = ">=1.3.11,<2"
compilers = ">=1.9.0,<2"
pkg-config = ">=0.29.2,<0.30"
cmake = ">=4.0.2,<5"
ninja = ">=1.12.1,<2"
ros-humble-turtlesim = ">=1.4.2,<2"
colcon-common-extensions = ">=0.3.0,<0.4"
setuptools = "<=58.2.0"
nanobind = ">=2.7.0,<3"
pinocchio = ">=3.7.0,<4"
dartsim-cpp = ">=6.15.0,<7"

# Support for DART GUI (maybe not all are needed)
glfw = ">=3.4,<4"
libopengl = ">=1.7.0,<2"
mesa-libgl-devel-cos7-x86_64 = ">=18.3.4,<19"
mesa-libglu-devel-cos7-x86_64 = ">=9.0.0,<10"
imgui = ">=1.91.9,<2"
mesa = ">=3.2.0,<4"
openscenegraph = ">=3.6.5,<4"
vulkan-tools = ">=1.4.304,<2"
vulkan-headers = ">=1.3.231.1,<2"
vulkan-validation-layers = ">=1.4.304,<2"
vulkan-memory-allocator = ">=3.1.0,<4"

[pypi-dependencies]
opencv-python = "==4.10.0"
umsgpack = ">=0.1.0, <0.2"
empy = "==3.3.4"
catkin-pkg = ">=1.0.0, <2"
