[project]
authors = ["neverorfrog <97flavio.maiorana@gmail.com>"]
channels = ["robostack-humble", "conda-forge"]
description = "Add a short description here"
name = "ismpc-ros2"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
build = {cmd = "colcon build", inputs = ["src"]}
clean = "rm -rf install log build"
ismpc = "ros2 launch ismpc_ros_client ismpc.launch.py"
# build-run-ismpc = "colcon build && ros2 launch ismpc_client ismpc.launch.py"

[activation]
scripts = ["install/setup.sh"]

[dependencies]
python = "3.11.*"
ros-humble-desktop = ">=0.10.0,<0.11"
ros-humble-ament-cmake-auto = ">=1.3.11,<2"
compilers = ">=1.9.0,<2"
pkg-config = ">=0.29.2,<0.30"
cmake = ">=4.0.2,<5"
ninja = ">=1.12.1,<2"
ros-humble-turtlesim = ">=1.4.2,<2"
colcon-common-extensions = ">=0.3.0,<0.4"
setuptools = "<=58.2.0"
nanobind = ">=2.7.0,<3"
pinocchio = ">=3.7.0,<4"

[pypi-dependencies]
opencv-python = "==4.10.0"
umsgpack = ">=0.1.0, <0.2"
empy = "==3.3.4"
catkin-pkg = ">=1.0.0, <2"
